variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: "300"
  GIT_SSL_NO_VERIFY: "true"
  S3_BUCKET_NAME: "ayab-debug"

stages:
  - build
  - deploy

cache:
  paths:
  - /Library/Caches/Homebrew
  - ~/.cache/pip

before_script:
  - TAG=$(git describe --tags | sed 's/-/.post/' | cut -f1 -d'-')
  - echo $TAG > src/main/resources/base/ayab/package_version
  - cat src/main/resources/base/ayab/package_version

build:osx:
  tags:
    - osx
    - virtualbox
  stage: build
  artifacts:
    when: always
    paths:
    - dist/release/
  script: 
  - mac-build/build.sh
  after_script:
  - ls -lisa dist/release

build:linux:
  image: python:3.5
  tags:
    - linux
    - docker
  stage: build
  artifacts:
    when: always
    paths:
    - dist/release/
  script:
  - linux-build/build.sh
  after_script:
  - ls -lisa dist/release

#build:win7:
#  tags:
#    - win7
#    - virtualbox
#  stage: build
#  artifacts:
#    when: always
#    paths:
#    - dist/release/
#  script:
#  - windows-build/build.sh 7
#  after_script:
#  - cd dist/release
#  - ls
# - cd ../..

build:win10:
  tags:
    - win10
    - virtualbox
  stage: build
  artifacts:
    when: always
    paths:
    - dist/release/
  script:
  - windows-build/build.sh 10
  after_script:
  - ls -lisa dist/release

#deploy:s3:
#  tags:
#    - linux
#    - docker
#  stage: deploy
#  environment:
#    name: s3
#    url: http://ayab-debug.s3-website.eu-central-1.amazonaws.com
#  image: python:latest
#  before_script:
#  - cp deploy/*.tpl dist/
#  - cd dist/release
#  - for i in `ls`; do echo "<li class=\"file\"><a href=\"$i\">$i</a></li>"; done > ../main.tpl
#  - cd ../
#  - cat header.tpl main.tpl footer.tpl > release/index.html
#  - cd ../
#  script:
#  - pip install awscli
# - aws s3 rm s3://$S3_BUCKET_NAME/ --recursive
#  - aws s3 cp --acl public-read ./dist/release/ s3://$S3_BUCKET_NAME/ --recursive

#deploy:github:
#  tags:
#    - linux
#    - docker
#  stage: deploy
#  environment:
#    name: github
#    url: https://github.com/AllYarnsAreBeautiful/ayab-desktop/releases
#  image: python:latest
#  script:
#  - cd dist/release
#  - ls
#  - /tools/upload.sh $CI_COMMIT_TAG master
#  only:
#  - tags
