repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.1.0
      hooks:
          - id: check-yaml
    - repo: https://github.com/psf/black-pre-commit-mirror
      rev: 24.3.0
      hooks:
          - id: black
            language_version: python3.11
    - repo: https://github.com/pycqa/flake8
      rev: '7.0.0'
      hooks:
      -   id: flake8
          additional_dependencies: [flake8-bugbear,flake8-sfs]
    - repo: local
      hooks:
      -   id: mypy
          name: check types with mypy
          language: system
          pass_filenames: false
          entry: mypy src
          files: ^src/.*.py$