name: Init Environment
runs:
  using: "composite"
  steps:
    - name: Set variables
      id: vars
      shell: bash
      run: |
        echo "sha-short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        echo "tag=$(git describe --tags)" >> $GITHUB_OUTPUT
        echo "draft=$(git describe --tags | sed -e 's/^test.*/true/;s/^v.*/false/')" >> $GITHUB_OUTPUT
        echo "manifest=$(cat src/main/resources/base/ayab/firmware/manifest.txt)" >> $GITHUB_OUTPUT
    - name: Set PACKAGE_VERSION
      shell: bash
      run: |
        echo ${{ steps.vars.outputs.tag }} > src/main/resources/base/ayab/package_version
        # remove suffix from semver tag, as fbs does not support them
        version_without_suffix=$(echo ${{ steps.vars.outputs.tag }} | sed -E 's/^v?([0-9]+\.[0-9]+\.[0-9]+).*$/\1/')
        sed -i -e s/PACKAGE_VERSION/$version_without_suffix/ src/build/settings/base.json
    - name: Set up Python ${{ matrix.python-version }}
      id: py
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
