name: decache
description: Restore cached files
runs:
  using: "composite"
inputs:
  python-version:
    required: true
  steps:
  - name: Set variables
    id: vars
    shell: bash
    run: |
      cd git
      echo "tag=$(git describe --tags)" >> $GITHUB_OUTPUT
      echo "python=python${{inputs.python-version}}" >> $GITHUB_OUTPUT
      echo "manifest=$(cat src/main/resources/base/ayab/firmware/manifest.txt)" >> $GITHUB_OUTPUT
  - name: Restore cached firmware
    id:   firmware-cache
    uses: actions/cache@v3
    with:
      path: src/main/resources/base/ayab/firmware/*.hex
      key: firmware-${{ steps.vars.outputs.manifest }}
      fail-on-cache-miss: true
  - name: Restore cached gui files (1)
    id:   gui1-cache
    uses: actions/cache@v3
    with:
      path: src/main/python/ayab/*_gui.py
      key:  gui1-${{ hashFiles('src/main/python/ayab/*_gui.ui') }}
      fail-on-cache-miss: true
  - name: Restore cached gui files (2)
    id:   gui2-cache
    uses: actions/cache@v3
    with:
      path: src/main/python/ayab/engine/*_gui.py
      key:  gui2-${{ hashFiles('src/main/python/ayab/engine/*_gui.ui') }}
      fail-on-cache-miss: true
  - name: Restore cached logo
    id:   logo-cache
    uses: actions/cache@v3
    with:
      path: src/main/python/ayab/ayab_logo_rc.py
      key:  logo-${{ hashFiles('src/main/python/ayab/ayab_logo_rc.qrc') }}
      fail-on-cache-miss: true
  - name: Restore cached translation files
    id:   qm-cache
    uses: actions/cache@v3
    with:
      path: src/main/resources/base/ayab/translations/*.qm
      key:  qm-${{ hashFiles('src/main/resources/base/ayab/translations/ayab-translation-master.tsv') }}
      fail-on-cache-miss: true
  - name: Restore cached `base.json` file
    id:   base-cache
    uses: actions/cache@v3
    with:
      path: src/build/settings/base.json
      key:  base-${{ steps.vars.outputs.tag }}
      enableCrossOsArchive: true
      fail-on-cache-miss: true
  - name: Remove unneeded files
    shell: bash
    run: |
      rm src/main/python/ayab/*_gui.ui
      rm src/main/python/ayab/ayab_logo_rc.qrc
  - name: Check cached files
    shell: bash
    run: |
      pwd
      ls -l src/main/python/ayab/
      ls -l src/main/resources/base/ayab/translations/
