# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ayab_gui.ui'
#
# Created by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1138, 856)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.assistant_dock = QtGui.QScrollArea(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.assistant_dock.sizePolicy().hasHeightForWidth())
        self.assistant_dock.setSizePolicy(sizePolicy)
        self.assistant_dock.setFrameShadow(QtGui.QFrame.Plain)
        self.assistant_dock.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.assistant_dock.setWidgetResizable(False)
        self.assistant_dock.setObjectName(_fromUtf8("assistant_dock"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setGeometry(QtCore.QRect(0, 0, 555, 791))
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.widget = QtGui.QWidget(self.dockWidgetContents)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.module_dropdown = QtGui.QComboBox(self.widget)
        self.module_dropdown.setObjectName(_fromUtf8("module_dropdown"))
        self.verticalLayout.addWidget(self.module_dropdown)
        self.load_file_button = QtGui.QPushButton(self.widget)
        self.load_file_button.setObjectName(_fromUtf8("load_file_button"))
        self.verticalLayout.addWidget(self.load_file_button)
        self.filename_lineedit = QtGui.QLineEdit(self.widget)
        self.filename_lineedit.setText(_fromUtf8(""))
        self.filename_lineedit.setObjectName(_fromUtf8("filename_lineedit"))
        self.verticalLayout.addWidget(self.filename_lineedit)
        self.verticalLayout_5.addWidget(self.widget)
        self.widget_2 = QtGui.QWidget(self.dockWidgetContents)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.line = QtGui.QFrame(self.widget_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_2.addWidget(self.line)
        self.knitting_options_dock = QtGui.QDockWidget(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.knitting_options_dock.sizePolicy().hasHeightForWidth())
        self.knitting_options_dock.setSizePolicy(sizePolicy)
        self.knitting_options_dock.setObjectName(_fromUtf8("knitting_options_dock"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.knitting_options_dock.setWidget(self.dockWidgetContents_2)
        self.verticalLayout_2.addWidget(self.knitting_options_dock)
        self.verticalLayout_5.addWidget(self.widget_2)
        self.line_2 = QtGui.QFrame(self.dockWidgetContents)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_5.addWidget(self.line_2)
        self.widget_3 = QtGui.QWidget(self.dockWidgetContents)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.knit_button = QtGui.QPushButton(self.widget_3)
        self.knit_button.setObjectName(_fromUtf8("knit_button"))
        self.verticalLayout_3.addWidget(self.knit_button)
        self.verticalLayout_5.addWidget(self.widget_3)
        self.assistant_dock.setWidget(self.dockWidgetContents)
        self.gridLayout.addWidget(self.assistant_dock, 0, 1, 3, 1)
        self.image_side_panel = QtGui.QVBoxLayout()
        self.image_side_panel.setObjectName(_fromUtf8("image_side_panel"))
        self.widget_6 = QtGui.QWidget(self.centralwidget)
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_6)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.widget_6)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.dimensions_label = QtGui.QLabel(self.widget_6)
        self.dimensions_label.setText(_fromUtf8(""))
        self.dimensions_label.setObjectName(_fromUtf8("dimensions_label"))
        self.horizontalLayout_2.addWidget(self.dimensions_label)
        self.image_side_panel.addWidget(self.widget_6)
        self.image_pattern_view = QtGui.QGraphicsView(self.centralwidget)
        self.image_pattern_view.setObjectName(_fromUtf8("image_pattern_view"))
        self.image_side_panel.addWidget(self.image_pattern_view)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.image_side_panel.addWidget(self.progressBar)
        self.gridLayout.addLayout(self.image_side_panel, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1138, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuImage_Actions = QtGui.QMenu(self.menubar)
        self.menuImage_Actions.setObjectName(_fromUtf8("menuImage_Actions"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_AYAB_Firmware = QtGui.QAction(MainWindow)
        self.actionLoad_AYAB_Firmware.setObjectName(_fromUtf8("actionLoad_AYAB_Firmware"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionOpen_Knitting_Project = QtGui.QAction(MainWindow)
        self.actionOpen_Knitting_Project.setObjectName(_fromUtf8("actionOpen_Knitting_Project"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionInvert = QtGui.QAction(MainWindow)
        self.actionInvert.setObjectName(_fromUtf8("actionInvert"))
        self.actionMirror = QtGui.QAction(MainWindow)
        self.actionMirror.setObjectName(_fromUtf8("actionMirror"))
        self.actionRotate_Left = QtGui.QAction(MainWindow)
        self.actionRotate_Left.setObjectName(_fromUtf8("actionRotate_Left"))
        self.actionRotate_Right = QtGui.QAction(MainWindow)
        self.actionRotate_Right.setObjectName(_fromUtf8("actionRotate_Right"))
        self.actionSmart_Resize = QtGui.QAction(MainWindow)
        self.actionSmart_Resize.setObjectName(_fromUtf8("actionSmart_Resize"))
        self.actionVertical_Flip = QtGui.QAction(MainWindow)
        self.actionVertical_Flip.setObjectName(_fromUtf8("actionVertical_Flip"))
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuTools.addAction(self.actionLoad_AYAB_Firmware)
        self.menuImage_Actions.addAction(self.actionInvert)
        self.menuImage_Actions.addSeparator()
        self.menuImage_Actions.addAction(self.actionVertical_Flip)
        self.menuImage_Actions.addAction(self.actionMirror)
        self.menuImage_Actions.addSeparator()
        self.menuImage_Actions.addAction(self.actionRotate_Left)
        self.menuImage_Actions.addAction(self.actionRotate_Right)
        self.menuImage_Actions.addSeparator()
        self.menuImage_Actions.addAction(self.actionSmart_Resize)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuImage_Actions.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "All Yarns Are Beautiful", None))
        self.assistant_dock.setWindowTitle(_translate("MainWindow", "Asistant", None))
        self.label_3.setText(_translate("MainWindow", "Load Images and Mode", None))
        self.load_file_button.setText(_translate("MainWindow", "Load Image File", None))
        self.knitting_options_dock.setWindowTitle(_translate("MainWindow", "Knitting Options", None))
        self.knit_button.setText(_translate("MainWindow", "Knit!", None))
        self.label_4.setText(_translate("MainWindow", "Image Dimensions", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuTools.setTitle(_translate("MainWindow", "Tools", None))
        self.menuImage_Actions.setTitle(_translate("MainWindow", "Image Actions", None))
        self.actionLoad_AYAB_Firmware.setText(_translate("MainWindow", "Load AYAB Firmware", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionOpen_Knitting_Project.setText(_translate("MainWindow", "Open Knitting Project", None))
        self.actionAbout.setText(_translate("MainWindow", "Help - About", None))
        self.actionHelp.setText(_translate("MainWindow", "Help", None))
        self.actionInvert.setText(_translate("MainWindow", "Invert", None))
        self.actionMirror.setText(_translate("MainWindow", "Mirror", None))
        self.actionRotate_Left.setText(_translate("MainWindow", "Rotate Left", None))
        self.actionRotate_Right.setText(_translate("MainWindow", "Rotate Right", None))
        self.actionSmart_Resize.setText(_translate("MainWindow", "Smart Resize", None))
        self.actionVertical_Flip.setText(_translate("MainWindow", "Vertical Flip", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

