# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'smart_resize.ui'
#
# Created: Thu Jan 26 21:53:32 2017
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(668, 331)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 4, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.vertical_stitches_label = QtWidgets.QLabel(Dialog)
        self.vertical_stitches_label.setText("")
        self.vertical_stitches_label.setObjectName("vertical_stitches_label")
        self.gridLayout.addWidget(self.vertical_stitches_label, 2, 5, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 5, 5, 1, 1)
        self.calculated_height_label = QtWidgets.QLabel(Dialog)
        self.calculated_height_label.setText("")
        self.calculated_height_label.setObjectName("calculated_height_label")
        self.gridLayout.addWidget(self.calculated_height_label, 4, 5, 1, 1)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 6, 4, 1, 1)
        self.ratio_label = QtWidgets.QLabel(Dialog)
        self.ratio_label.setText("")
        self.ratio_label.setObjectName("ratio_label")
        self.gridLayout.addWidget(self.ratio_label, 0, 2, 1, 1)
        self.ratios_list = QtWidgets.QListWidget(Dialog)
        self.ratios_list.setObjectName("ratios_list")
        self.gridLayout.addWidget(self.ratios_list, 1, 3, 5, 1)
        self.width_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.width_spinbox.setSingleStep(0.1)
        self.width_spinbox.setObjectName("width_spinbox")
        self.gridLayout.addWidget(self.width_spinbox, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 3)
        self.calculated_width_label = QtWidgets.QLabel(Dialog)
        self.calculated_width_label.setText("")
        self.calculated_width_label.setObjectName("calculated_width_label")
        self.gridLayout.addWidget(self.calculated_width_label, 3, 5, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 4, 1, 1)
        self.height_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.height_spinbox.setSingleStep(0.1)
        self.height_spinbox.setObjectName("height_spinbox")
        self.gridLayout.addWidget(self.height_spinbox, 3, 2, 1, 1)
        self.horizontal_stitches_label = QtWidgets.QLabel(Dialog)
        self.horizontal_stitches_label.setText("")
        self.horizontal_stitches_label.setObjectName("horizontal_stitches_label")
        self.gridLayout.addWidget(self.horizontal_stitches_label, 1, 5, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "Calculated Height"))
        self.label_2.setText(_translate("Dialog", "Calculated Horizontal Stitches"))
        self.label.setText(_translate("Dialog", "Ratio"))
        self.label_7.setText(_translate("Dialog", "Physical Height"))
        self.label_6.setText(_translate("Dialog", "Proposed Aproximate Ratios"))
        self.label_9.setText(_translate("Dialog", "Physical Width"))
        self.label_8.setText(_translate("Dialog", "Input Width and Height in cm"))
        self.label_5.setText(_translate("Dialog", "Calculated Width"))
        self.label_4.setText(_translate("Dialog", "Calculated Vertical Stitches"))

