# This workflow builds the AYAB Windows Installer and stores it as an artifact

name: Build

on:
  push:
    branches:
      - master
      - '*-dev'

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Set GIT_TAG variable
      run: |
        echo "::set-env name=GIT_TAG::$(git describe --tags)"
    - name: Set PACKAGE_VERSION
      run: |
        echo ${{env.GIT_TAG}} > src/main/resources/base/ayab/package_version
        sed -i 's/PACKAGE_VERSION/${{env.GIT_TAG}}/' src/build/settings/base.json
        cat src/main/resources/base/ayab/package_version
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install -r windows-build\windows_build_requirements.txt
    - name: Convert UI and translation files
      run: |
        ./setup-environment.sh
    - name: Build app
      run: |
        python -m fbs freeze --debug
    - name: Create installer
      run: |
        python -m fbs installer
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: AYABSetup-${{env.GIT_TAG}}
        path: target/AYABSetup.exe
